name: Terraform Workloads Destroy

on:
  workflow_dispatch:

jobs:
  destroy-workloads:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout infra-terraform
        uses: actions/checkout@v4
        with:
          path: infra-terraform

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246412345195:role/github-actions-deploy-role
          aws-region: us-east-1

      - name: Confirm AWS Credentials
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl
          aws --version

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --region us-east-1 --name shopsphere-dev-eks

      - name: Terraform Init
        run: |
          cd infra-terraform/envs/dev/workloads
          terraform init

      - name: Terraform Destroy
        run: |
          cd infra-terraform/envs/dev/workloads
          terraform destroy -auto-approve
