name: Terraform Infra Destroy

on:
  workflow_dispatch:

jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout infra-terraform
        uses: actions/checkout@v4
        with:
          path: infra-terraform

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::246412345195:role/github-actions-deploy-role
          aws-region: us-east-1

      - name: Confirm AWS Credentials
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          cd infra-terraform/envs/dev/infra
          terraform init

      - name: Remove Secret from Terraform State
        run: |
          cd infra-terraform/envs/dev/infra
          terraform state rm 'module.rds.aws_secretsmanager_secret.db' || true

      - name: Terraform Destroy
        run: |
          cd infra-terraform/envs/dev/infra
          terraform destroy -auto-approve
